version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: telegrambot-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: top1love
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
